require:
  - rubocop-rspec
  - rubocop-performance
Rails:
  Enabled: true
AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'bin/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'lib/tasks/*'
    - 'script/**/*'
    - 'spec/**/*.rb'
    - 'vendor/**/*'

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods
Style/Documentation:
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
Style/RescueStandardError:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
# Metrics/AbcSize:
#   Enabled: false
Metrics/ClassLength:
  Enabled: false
# Metrics/MethodLength:
#   Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
