require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rails
Rails:
  Enabled: true
AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - bin/*
    - config/**/*
    - db/**/*
    - lib/tasks/*
    - script/**/*
    - vendor/**/*

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods
Lint/ElseLayout:
  Enabled: false
Metrics/AbcSize:
  Exclude:
    - app/graphql/mutations/base_*_mutation.rb
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  CountAsOne: ['array', 'hash', 'heredoc']
  Exclude:
    - app/controllers/graphql_controller.rb
    - app/graphql/mutations/base_*_mutation.rb
Metrics/BlockLength:
  CountAsOne: ['array', 'hash']
  Exclude:
    - app/graphql/mutations/base_*_mutation.rb
Style/Documentation:
  Enabled: false
Style/RescueStandardError:
  Enabled: false
Style/HashAsLastArrayItem:
  EnforcedStyle: no_braces
