require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rails
Rails:
  Enabled: true
AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - bin/*
    - config/**/*
    - db/**/*
    - lib/tasks/*
    - script/**/*
    - vendor/**/*

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods
Layout/LineLength:
  Max: 80
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Lint/MixedRegexpCaptureTypes:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Metrics/AbcSize:
  Exclude:
    - app/graphql/mutations/add_mutations.rb
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  CountAsOne: ['array', 'hash']
  Exclude:
    - app/controllers/graphql_controller.rb
    - app/graphql/mutations/add_mutations.rb
Metrics/BlockLength:
  CountAsOne: ['array', 'hash']
  Exclude:
    - app/graphql/mutations/add_mutations.rb
Style/Documentation:
  Enabled: false
Style/ExponentialNotation:
  Enabled: true
Style/RedundantFetchBlock:
  Enabled: true
Style/RedundantRegexpCharacterClass:
  Enabled: true
Style/RedundantRegexpEscape:
  Enabled: true
Style/SlicingWithRange:
  Enabled: true
Style/TrailingCommaInArguments:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
Style/RescueStandardError:
  Enabled: false
Style/HashAsLastArrayItem:
  EnforcedStyle: no_braces
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
