require: rubocop-rspec
Rails:
  Enabled: true
AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'bin/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'lib/tasks/*'
    - 'script/**/*'
    - 'spec/**/*.rb'
    - 'vendor/**/*'

Layout/IndentationConsistency:
  EnforcedStyle: rails
Style/Documentation:
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
Style/RescueStandardError:
  Enabled: false
Rails/FindEach:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: false
# Metrics/AbcSize:
#   Enabled: false
Metrics/ClassLength:
  Enabled: false
# Metrics/MethodLength:
#   Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
