redis: &redis
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>

development:
  <<: *redis
  channel_prefix: development

test:
  adapter: async

production:
  <<: *redis
  channel_prefix: production
