default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  timeout: 5000
  host: localhost
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

test:
  <<: *default
  database: myfifa_test

development:
  <<: *default
  database: myfifa_dev

production:
  <<: *default
  database: myfifa_pro
