# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  timeout: 5000
  host: localhost
  username: <%= ENV['db_username'] %>
  password: <%= ENV['db_password'] %>

test:
  <<: *default
  database: myfifa_api_test

development:
  <<: *default
  database: myfifa_api_dev

production:
  <<: *default
  database: myfifa_api_pro
