inherit_from:
  - ../.rubocop.yml
Layout/LineLength:
  Max: 100
Metrics/BlockLength:
  Enabled: false
RSpec/BeforeAfterAll:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
Style/BlockComments:
  Exclude:
    - spec_helper.rb
